-- CREATE TABLE Houses (
-- 	ID SERIAL PRIMARY KEY,
-- 	Name VARCHAR(30),
-- 	Address VARCHAR(100),
-- 	City VARCHAR(100),
-- 	State VARCHAR(2),
-- 	Zip INTEGER,
-- 	Img TEXT,
-- 	Mortgage DECIMAL,
-- 	Rent DECIMAL
-- );

-- INSERT INTO Houses ( Name, Address, City, State, Zip, Img, Mortgage, Rent)
-- VALUES ('Black House', '12121 Somewhere Blvd', 'ChangTon', 'CA', '90210', 'No Image', 2500.37, 3000),
-- ('Green House', '2020 California Ave', 'Sandy', 'UT', '84070', 'No Image', 1513.06, 2200)